#!/usr/bin/env python3
"""
conformance.py  (v0.1.0)

Emits a structured conformance report for the CSIS machine-readable layer:
csis-conformance.json. Zero external dependencies (standard library only).

The report answers "does the published machine-readable layer conform to its own
contract and to source," which is the part of conformance a machine can settle. It
declares, rather than hides, what it cannot check: whether an external coordination
system conforms to a standard is interpretive and belongs to the audit prompts and
skills, not to this layer.

Run: python3 standards/machine-readable/conformance.py
Exit codes: 0 all checks pass, 1 one or more checks fail.
"""

import json
import sys
from pathlib import Path

import validate as validator

HERE = Path(__file__).resolve().parent
STANDARDS_DIR = HERE.parent
SCHEMA = HERE / "standards-family-manifest.schema.json"
MANIFEST = HERE / "csis-manifest.json"
OUT = HERE / "csis-conformance.json"


def run_checks(manifest, schema):
    checks = []

    # 1. schema contract
    errors = validator.validate(manifest, schema)
    checks.append({
        "check": "schema-valid",
        "status": "pass" if not errors else "fail",
        "detail": "manifest conforms to standards-family-manifest.schema.json"
                  if not errors else f"{len(errors)} contract error(s)",
        "errors": errors,
    })

    members = manifest.get("members", [])
    published = [m for m in members if m.get("status") == "published"]
    candidates = [m for m in members if m.get("status") == "candidate"]

    # 2. member census (informational)
    checks.append({
        "check": "member-census",
        "status": "info",
        "detail": f"{len(members)} members: {len(published)} published, {len(candidates)} candidate",
    })

    # 3. candidates all carry candidate status and a not-promoted description
    unmarked = [m.get("id") for m in candidates
                if "not promoted" not in (m.get("description", "").lower())]
    checks.append({
        "check": "candidate-status-marked",
        "status": "pass" if not unmarked else "fail",
        "detail": "every candidate carries candidate status and a not-promoted description"
                  if not unmarked else f"candidates missing not-promoted marker: {unmarked}",
    })

    # 4. candidate canonicalSource files exist locally (published ones point at the
    #    public repo and are not resolvable here, so only candidates are checkable)
    missing = []
    for m in candidates:
        src = m.get("canonicalSource", "")
        # canonicalSource is corpus-relative, e.g. standards/standards-candidates/...
        rel = src[len("standards/"):] if src.startswith("standards/") else src
        if not (STANDARDS_DIR / rel).exists():
            missing.append({"id": m.get("id"), "canonicalSource": src})
    checks.append({
        "check": "candidate-source-present",
        "status": "pass" if not missing else "fail",
        "detail": "every candidate canonicalSource resolves to an existing file"
                  if not missing else f"{len(missing)} candidate source(s) missing",
        "missing": missing,
    })

    return checks


def main():
    schema = json.loads(SCHEMA.read_text(encoding="utf-8"))
    manifest = json.loads(MANIFEST.read_text(encoding="utf-8"))
    checks = run_checks(manifest, schema)

    failed = [c for c in checks if c["status"] == "fail"]
    report = {
        "$comment": "GENERATED by standards/machine-readable/conformance.py. Structured conformance of the CSIS machine-readable layer against its own contract and source.",
        "family": manifest.get("name"),
        "manifestVersion": manifest.get("version"),
        "generatedBy": "standards/machine-readable/conformance.py",
        "result": "pass" if not failed else "fail",
        "checks": checks,
        "declaredUncheckable": [
            "Whether an external coordination system conforms to a standard is interpretive and out of scope for this machine layer. Use the audit prompts (standards/prompts) and skills (standards/claude-skills).",
            "Published-standard canonicalSource resolves to the public suite repository and is not checked for existence locally.",
            "Source version drift (filename versus header, stale secondary stamps) is caught at generate time by standards/tools/generate-csis-manifest.py, not re-checked here.",
        ],
    }
    OUT.write_text(json.dumps(report, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    print(f"conformance: {report['result']} ({len(checks)} checks, {len(failed)} failed)")
    for c in checks:
        print(f"  [{c['status']}] {c['check']}: {c['detail']}")
    print(f"wrote: {OUT.relative_to(STANDARDS_DIR)}")
    return 1 if failed else 0


if __name__ == "__main__":
    sys.exit(main())
